/**
 * @file TsInjectablePlugin
 * @author Jim Bulkowski <jim.b@paperelectron.com>
 * @project @framework
 * @license MIT {@link http://opensource.org/licenses/MIT}
 */

export const template = `// Generated by the Pomegranate cli on {{creationDate}}

const {ApplicationPlugin, InjectablePlugin} = require('pomegranate')

const MyPlugin = InjectablePlugin()
  .configuration({
    name: 'example',
    type: 'anything',
    injectableParam: 'example',
    depends: [],
    provides: [],
    optional: []
  })
  .variables({})
  .hooks({
    load: () => {
      return {}
    },
    start: () => {
      
    },
    stop: () => {
      
    }
  })
  .directories([])
  .commands(() => {
    
  })
  .installs()

export.Plugin = ApplicationPlugin()
  .configuration({
    name: '{{name}}',
    type: 'application',
    depends: [],
    provides: [],
    optional: []
  })
  .applicationPlugins([
    MyPlugin
  ])
`