/**
 * @file TsInjectablePlugin
 * @author Jim Bulkowski <jim.b@paperelectron.com>
 * @project @framework
 * @license MIT {@link http://opensource.org/licenses/MIT}
 */

export const template = `// Generated by the Pomegranate cli on {{creationDate}}

import {InjectablePlugin} from 'pomegranate'

export const Plugin = InjectablePlugin()
  .configuration({
    name: '{{name}}',
    type: '{{type}}',
    injectableParam: '{{name}}',
    depends: [],
    provides: [],
    optional: []
  })
  .variables({})
  .hooks({
    load: () => {
      return {}
    },
    start: () => {
      
    },
    stop: () => {
      
    }
  })
  .directories([])
  .commands(() => {
    
  })
  .installs()
`