/**
 * @file TsInjectablePlugin
 * @author Jim Bulkowski <jim.b@paperelectron.com>
 * @project @framework
 * @license MIT {@link http://opensource.org/licenses/MIT}
 */
export declare const template = "// Generated by the Pomegranate cli on {{creationDate}}\n\nconst {InjectablePlugin} = require('pomegranate')\n\nexports.Plugin = InjectablePlugin()\n  .configuration({\n    name: '{{name}}',\n    type: '{{type}}',\n    injectableParam: '{{name}}',\n    depends: [],\n    provides: [],\n    optional: []\n  })\n  .variables({})\n  .hooks({\n    load: () => {\n      return {}\n    },\n    start: () => {\n      \n    },\n    stop: () => {\n      \n    }\n  })\n  .directories([])\n  .commands(() => {\n    \n  })\n  .installs()\n";
