import { ApplicationPluginTypes, ApplicationBuilder, PomApplicationPlugin } from './builders/ApplicationBuilder';
import { CommandPluginTypes, CommandBuilder, PomCommandPlugin } from "./builders/CommandBuilder";
import { CompositePluginTypes, CompositeBuilder, PomCompositePlugin } from "./builders/CompositeBuilder";
import { ActionBuilder, ActionPluginTypes, PomActionPlugin } from "./builders/ActionBuilder";
import { InjectableBuilder, InjectablePluginTypes, PomInjectablePlugin } from "./builders/InjectableBuilder";
import { LoghandlerBuilder, LoghandlerPluginTypes, PomLogHandlerPlugin } from "./builders/LoghandlerBuilder";
import { OverridePluginTypes, OverrideBuilder, PomOverridePlugin } from "./builders/OverrideBuilder";
import { PomegranatePlugin } from "./PluginTypes";
export declare type BuildableType = ApplicationPluginTypes | CompositePluginTypes | CommandPluginTypes | ActionPluginTypes | InjectablePluginTypes | LoghandlerPluginTypes | OverridePluginTypes;
export declare function isBuildableType(builderName: string | PomegranatePlugin): builderName is BuildableType;
export declare function isPomegranateType(pomPlugin: PomegranatePlugin | any): pomPlugin is PomegranatePlugin;
export declare function CreatePlugin(builderType: ActionPluginTypes): ActionBuilder;
export declare function CreatePlugin(builderType: PomActionPlugin): ActionBuilder;
export declare function CreatePlugin(builderType: ApplicationPluginTypes): ApplicationBuilder;
export declare function CreatePlugin(builderType: PomApplicationPlugin): ApplicationBuilder;
export declare function CreatePlugin(builderType: InjectablePluginTypes): InjectableBuilder;
export declare function CreatePlugin(builderType: PomInjectablePlugin): InjectableBuilder;
export declare function CreatePlugin(builderType: CommandPluginTypes): CommandBuilder;
export declare function CreatePlugin(builderType: PomCommandPlugin): CommandBuilder;
export declare function CreatePlugin(builderType: CompositePluginTypes): CompositeBuilder;
export declare function CreatePlugin(builderType: PomCompositePlugin): CompositeBuilder;
export declare function CreatePlugin(builderType: LoghandlerPluginTypes): LoghandlerBuilder;
export declare function CreatePlugin(builderType: PomLogHandlerPlugin): LoghandlerBuilder;
export declare function CreatePlugin(builderType: OverridePluginTypes): OverrideBuilder;
export declare function CreatePlugin(builderType: PomOverridePlugin): OverrideBuilder;
